# Generated by Django 3.2.9 on 2021-12-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211208_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datecompleted',
        ),
    ]
